### ISSUE TITLE
Improve code coverage. 

### ISSUE THREAD

**Issue by branimir-kirilov** [cwetanow/Logs#1]
I noticed that your code coverage is extremely low (about 88%). Please consider improving your tests.

**Comment by cwetanow** [comment]
Probably you are seeing an older version. Currently it is above 90%. Please check your facts! [![Coverage Status](https://coveralls.io/repos/github/cwetanow/Logs/badge.svg?branch=master)](https://coveralls.io/github/cwetanow/Logs?branch=master)
